title: Aketza Romaniega
logo: /images/unnamed.jpg
description: Portfolio of Aketza Romaniega, a Junior Data Scientist and Analyst with a background in bioinformatics, biostatistics and chemistry.
theme: jekyll-theme-minimal
